# Generated by Django 6.0.3 on 2026-03-22 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du groupe')),
                ('category', models.CharField(choices=[('covers', 'Covers'), ('branding', 'Logo & Branding'), ('videos', 'Vidéos'), ('affiches', 'Affiches'), ('miniatures', 'Miniatures'), ('bannieres', 'Bannières')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Groupe',
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('category', models.CharField(choices=[('covers', 'Covers'), ('branding', 'Logo & Branding'), ('videos', 'Vidéos'), ('affiches', 'Affiches'), ('miniatures', 'Miniatures'), ('bannieres', 'Bannières')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, help_text='Optionnel — laisser vide si le projet est indépendant', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='portfolio.group', verbose_name='Groupe (album / pack)')),
            ],
            options={
                'verbose_name': 'Projet',
                'ordering': ['category', 'group__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/')),
                ('order', models.PositiveIntegerField(default=0, help_text="Ordre d'affichage")),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='portfolio.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Image',
                'ordering': ['order'],
            },
        ),
    ]
