# Generated by Django 6.0.3 on 2026-03-22 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['group__order', 'order'], 'verbose_name': 'Projet'},
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('covers', 'Covers'), ('branding', 'Logo & Branding'), ('videos', 'Vidéos'), ('affiches', 'Affiches'), ('miniatures', 'Miniatures'), ('bannieres', 'Bannières')], help_text='Laisser vide si un groupe est sélectionné', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Optionnel — laisser vide si le projet est solo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='portfolio.group', verbose_name='Groupe (album / pack)'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
