# Generated by Django 6.0.3 on 2026-03-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_project_options_alter_project_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(blank=True, help_text='Optionnel si un groupe est sélectionné — le nom du groupe sera utilisé', max_length=200, null=True, verbose_name='Titre'),
        ),
    ]
