# Generated by Django 6.0.3 on 2026-03-22 18:51

import portfolio.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_project_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(upload_to=portfolio.models.project_image_path),
        ),
    ]
