# Generated by Django 6.0.3 on 2026-03-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_projectimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL YouTube'),
        ),
        migrations.AddField(
            model_name='project',
            name='yt_published',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Date de publication'),
        ),
        migrations.AddField(
            model_name='project',
            name='yt_thumbnail',
            field=models.URLField(blank=True, default='', verbose_name='Miniature YouTube'),
        ),
        migrations.AddField(
            model_name='project',
            name='yt_title',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='project',
            name='yt_views',
            field=models.PositiveIntegerField(default=0, verbose_name='Vues'),
        ),
    ]
