# Generated by Django 6.0.3 on 2026-03-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_project_youtube_url_project_yt_published_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='group',
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['category', 'order'], 'verbose_name': 'Projet'},
        ),
        migrations.AddField(
            model_name='project',
            name='sub_type',
            field=models.CharField(choices=[('single', 'Single'), ('album', 'Album'), ('logo', 'Logo'), ('branding', 'Branding'), ('affiche', 'Affiche'), ('pack', 'Pack'), ('miniature', 'Miniature'), ('minipack', 'Pack de miniatures'), ('video', 'Vidéo'), ('banniere', 'Bannière')], default='single', max_length=20, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('covers', 'Covers'), ('branding', 'Logo & Branding'), ('videos', 'Vidéos'), ('affiches', 'Affiches'), ('miniatures', 'Miniatures'), ('bannieres', 'Bannières')], default='covers', max_length=20, verbose_name='Catégorie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(default='sans titre', max_length=200, verbose_name='Titre'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
