# Generated by Django 6.0.3 on 2026-03-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_project_group_alter_project_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('covers', 'Covers'), ('branding', 'Logo & Branding'), ('videos', 'Lyrics Video'), ('affiches', 'Affiches'), ('miniatures', 'Miniatures YouTube'), ('bannieres', 'Bannières & Profils')], max_length=20)),
                ('subtype', models.CharField(max_length=30)),
                ('video_duration', models.CharField(blank=True, default='', max_length=20)),
                ('extra', models.TextField(blank=True, default='')),
                ('deadline', models.CharField(max_length=20)),
                ('budget', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('ai_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Devis',
                'verbose_name_plural': 'Devis',
                'ordering': ['-created_at'],
            },
        ),
    ]
