# Generated by Django 6.0.3 on 2026-03-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_client_siteconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='devis',
            name='currency',
            field=models.CharField(choices=[('FCFA', 'FCFA'), ('EUR', 'EUR'), ('USD', 'USD')], default='FCFA', max_length=5),
        ),
    ]
