# Generated by Django 6.0.3 on 2026-03-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_devis_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('covers', 'Covers'), ('branding', 'Logo & Branding'), ('videos', 'Lyrics Video'), ('affiches', 'Affiches'), ('miniatures', 'Miniatures YouTube'), ('bannieres', 'Bannières & Profils')], max_length=20, verbose_name='Catégorie')),
                ('subtype', models.CharField(help_text='ex: single, album_3d, logo, cinematique…', max_length=50, verbose_name='Sous-type')),
                ('label', models.CharField(help_text='Nom affiché dans le prompt Claude', max_length=100, verbose_name='Label')),
                ('price_fcfa', models.PositiveIntegerField(default=0, help_text='Prix de base en FCFA (sans supplément)', verbose_name='Prix (FCFA)')),
                ('note', models.TextField(blank=True, default='', help_text='Non envoyé au client — infos internes uniquement', verbose_name='Note interne')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Tarif de service',
                'verbose_name_plural': 'Tarifs de services',
                'ordering': ['category', 'order'],
            },
        ),
    ]
