# Generated by Django 6.0.3 on 2026-03-25 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_add_contact_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioPreviewSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile')], max_length=10, verbose_name='Écran')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('active', models.BooleanField(default=True, verbose_name='Actif')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preview_slots', to='portfolio.project', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Slot de prévisualisation',
                'verbose_name_plural': 'Slots de prévisualisation',
                'ordering': ['device', 'order'],
                'unique_together': {('project', 'device')},
            },
        ),
    ]
