# Generated by Django 6.0.3 on 2026-04-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_project_custom_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Meta description (SEO, max 160 car.)')),
                ('category', models.CharField(choices=[('branding', 'Branding'), ('tarifs', 'Tarifs'), ('process', 'Process'), ('tendances', 'Tendances'), ('musique', 'Musique')], max_length=100, verbose_name='Catégorie')),
                ('thumbnail', models.URLField(blank=True, default='', max_length=500, verbose_name='Thumbnail (URL Cloudinary)')),
                ('content', models.TextField(verbose_name='Contenu (markdown)')),
                ('published', models.BooleanField(default=True, verbose_name='Publié')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Article de blog',
                'verbose_name_plural': 'Articles de blog',
                'ordering': ['-published_at'],
            },
        ),
        migrations.AlterField(
            model_name='project',
            name='sub_type',
            field=models.CharField(choices=[('single', 'Single'), ('album', 'Album'), ('logo', 'Logo'), ('branding', 'Branding'), ('affiche', 'Affiche'), ('pack', 'Pack'), ('miniature', 'Miniature'), ('video', 'Vidéo'), ('banniere', 'Bannière')], default='single', max_length=20, verbose_name='Type'),
        ),
    ]
