# Generated by Django 6.0.3 on 2026-04-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_blogpost_alter_project_sub_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_en',
            field=models.TextField(blank=True, default='', verbose_name='Contenu EN (markdown)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Meta description EN'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Titre (EN)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('branding', 'Branding'), ('tendances', 'Tendances'), ('process', 'Process')], max_length=100, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(verbose_name='Contenu FR (markdown)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='description',
            field=models.TextField(verbose_name='Meta description FR (max 160 car.)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titre (FR)'),
        ),
    ]
