# Generated by Django 6.0.3 on 2026-04-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_blogpost_json_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.JSONField(default=list, help_text='Liste de blocs. Types disponibles :\n{"type":"heading","text":"TITRE"}\n{"type":"paragraph","text":"Texte avec **gras** et *violet*"}\n{"type":"image","url":"https://...","alt":"optionnel"}\n{"type":"link","text":"Texte du lien","url":"https://..."}\n{"type":"embed","url":"https://www.instagram.com/p/XYZ/","caption":"optionnel"}', verbose_name='Contenu FR'),
        ),
    ]
