# Generated by Django 6.0.3 on 2026-04-04 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_alter_blogpost_content'),
        ('portfolio', '0018_project_description'),
    ]

    operations = [
    ]
